### ISSUE TITLE
Error in Generating Executable Help Docs

### ISSUE THREAD

**Issue by ThePhisch** [rucio/documentation#241]
An error occurs in the building of the docs, see [here](https://github.com/rucio/documentation/actions/runs/5722502846/job/15505671476#step:5:157). The error message (shown below) leads to the conclusion that an outdated rucio version is used (inspecting the current rucio version in `common/config.py:197` shows that this line is not part of `config_get_float`, but this was the case in an earlier version).

```
Generating the Executable Help Docs...
Traceback (most recent call last):
  File "rucio/bin/rucio", line 2521, in <module>
    oparser = get_parser()
  File "rucio/bin/rucio", line 2308, in get_parser
    selected_parser.add_argument('--transfer-timeout', dest='transfer_timeout', type=float, action='store', default=config_get_float('download', 'transfer_timeout', False, None), help='Transfer timeout (in seconds). Default: computed dynamically from --transfer-speed-timeout. If set to any value >= 0, --transfer-speed-timeout is ignored.')  # NOQA: E501
  File "/usr/local/lib/python3.8/site-packages/rucio/common/config.py", line 197, in config_get_float
    return float(config_get(
TypeError: float() argument must be a string or a number, not 'NoneType'
```

Further proof of this can be seen in [`generate_dynamic_files.sh`](https://github.com/rucio/documentation/blob/73ac15cb196f7f5f5a2d65e9170bd14d38737f32/tools/generate_dynamic_files.sh#L8), which pulls an outdated tag.

**TASK**: fix the import by pulling the appropriate tag

**Comment by ThePhisch** [comment]
no fix required here.
