### ISSUE TITLE
Address deprecated deps and mitigate warnings

### ISSUE THREAD

**Issue by labkode** [rucio/documentation#405]
The CI gives some warnings about deprecated dependencies and some failures when building REST API for some sections. 
Example CI job with such failures:
https://github.com/rucio/documentation/actions/runs/12140139182/job/33849290666

Refer to "Build" step.

Snippet:
```
 Generating documentation files...
Generating the Rest Api Docs...
Generating the Executable Help Docs...
Traceback (most recent call last):
  File "/run_in_docker/rucio/bin/rucio-cache-client", line 123, in <module>
    oparser = get_parser()
  File "/run_in_docker/rucio/bin/rucio-cache-client", line 111, in get_parser
    oparser.add_argument('-b', '--broker', dest='broker', default=config_get('messaging-cache', 'brokers').split(',')[0], help='Message broker name')
  File "/opt/venv/lib64/python3.9/site-packages/rucio/common/config.py", line 210, in config_get
    raise err
  File "/opt/venv/lib64/python3.9/site-packages/rucio/common/config.py", line 191, in config_get
    return convert_type_fnc(get_config().get(section, option))
  File "/usr/lib64/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib64/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
```

**Comment by voetberg** [comment]
> Regarding the snippet in particular - this should go away once we migrate away from Pydoc: #377

That issue is only regarding the py client, the docs generated from rucio/bin are just from running `--help` on the executable, so they'll still be present. This can probably only be solved by putting a pr in gh.com/rucio/rucio
